### ISSUE TITLE
CreateOne doesn't work with directus 10.12.1

### ISSUE THREAD

**Issue by Litesoulo** [apstanisic/directus-dart#83]
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("data")

createOne and createMany doesn't work, when I have only create permission on collection

**Comment by Litesoulo** [comment]
Just closing
